/* 

"create a license": {
		"prefix": "licence",
		"body":[
"# MIT License",
"",
"Copyright (c) 2024 Williams Hernández",
"",

"**English version:**",
"",
"Permission is hereby granted, free of charge, to any person obtaining a copy",
"of this software and associated documentation files (the 'Software'), to deal",
"in the Software without restriction, including without limitation the rights",
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
"copies of the Software, and to permit persons to whom the Software is",
"furnished to do so, subject to the following conditions:",
"",
"The above copyright notice and this permission notice shall be included in all",
"copies or substantial portions of the Software.",
"",
"THE SOFTWARE IS PROVIDED \"AS IS WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
"SOFTWARE.\"",
"",
"**Versión Español:**",
"",
"\"Se otorga permiso, de forma gratuita, a cualquier persona que obtenga una copia de este software y los archivos de documentación asociados (el \"Software\"), para tratar con el Software sin restricción alguna, incluyendo sin limitación los derechos de usar, copiar, modificar, fusionar, publicar,", "distribuir, sublicenciar y/o vender copias del Software, y permitir a las personas a quienes se les proporcione el Software, hacerlo, sujeto a las siguientes condiciones:",
"",
"La presente notificación de derechos de autor y esta notificación de permiso deberán ser incluidas en todas las copias o porciones sustanciales del Software.",
"",
"EL SOFTWARE SE PROPORCIONA “TAL CUAL”, SIN GARANTÍA DE NINGÚN TIPO, EXPRESA O IMPLÍCITA, INCLUYENDO PERO NO LIMITADO A LAS GARANTÍAS DE COMERCIABILIDAD,", "IDONEIDAD PARA UN PROPÓSITO PARTICULAR Y NO INFRACCIÓN. EN NINGÚN CASO LOS AUTORES O TITULARES DE DERECHOS DE AUTOR SERÁN RESPONSABLES POR CUALQUIER", "RECLAMACIÓN, DAÑOS U OTRA RESPONSABILIDAD, YA SEA EN UNA ACCIÓN DE CONTRATO, AGRAVIO O DE OTRO TIPO, QUE SURJA DE, O EN CONEXIÓN CON EL SOFTWARE O EL USO U", "OTROS TRATOS EN EL SOFTWARE\"",
""
		]
	 },







*/

/*


"create a readme": {
	// 	"scope": "javascript,typescript",
	 	"prefix": "readme",
	 	"body": [

"# Titulo del proyecto",
"",
"Breve descripción del proyecto y su objetivo.",
"",
"## Descripción del proyecto",
"",
"¿Estás comenzando un proyecto pequeño, un desafío de programación o un tutorial, y necesitas una forma rápida y sencilla de crear documentación básica? ¡Esta plantilla README minimalista es para ti!",
"",
"## Capturas de Pantalla del Proyecto",
"",
"Incluir capturas de pantalla o imágenes que muestren el proyecto en funcionamiento.",
"",
"![Home](imagenes/home.png)",
"Vista inicio de la aplicación.",
"",
"## Prerrequisitos o Dependencias",
"",
"Lista de software y herramientas, incluyendo versiones, que necesitas para instalar y ejecutar este proyecto:",
"",
"- Sistema Operativo (por ejemplo, Ubuntu 20.04, Windows 10)",
"- Lenguaje de programación (por ejemplo, Python 3.8)",
"- Framework (por ejemplo, Django 3.1)",
"- Base de datos (por ejemplo, PostgreSQL 12)",
"- Otros...",
"",
"## Instalación del Proyecto",
"",
"Una guía paso a paso sobre cómo configurar el entorno de desarrollo e instalar todas las dependencias.",
"",
"```bash",
"# paso 1",
"```",
"",
"Y así sucesivamente...",
"",
"```bash",
"# paso 2",
"```",
"",
"## Instrucciones para Ejecutar el Proyecto",
"",
"Instrucciones para ejecutar el proyecto una vez instalado.",
"",
"```bash",
"#",
"```",
"",
"## Instrucciones para Cargar la Base de Datos o Migrar los Modelos",
"",
"Instrucciones necesario para cargar la base de datos o migrar los modelos de datos.",
"",
"```bash",
"#",
"```",
"",
"## Instrucciones para Cargar los Datos Semilla a la Base de Datos",
"",
"Comandos necesario para cargar los datos semilla a la base de datos.",
"",
"```bash",
"# paso 1",
"```",
"",
"Y así sucesivamente...",
"",
"```bash",
"# paso 2",
"```",
"",
"## Credenciales de Acceso",
"",
"### Para Usuario Tipo Administrador",
"",
"- Email: <administrador@mail.com>",
"- Contraseña: Abc123#",
"",
"### Para Usuario Tipo User",
"",
"- Email: <user@mail.com>",
"- Contraseña: Abc123#",
"",
"Menciona a todos aquellos que ayudaron a levantar el proyecto desde sus inicios",
"",
"- **Williams Hernández** - *Trabajo Inicial* - [Williams Hernández](https://github.com/hernandw)",
"- **Fulanito Detal** - *Documentación* - [fulanitodetal](https://github.com/juanito)",
"",
"## Licencia",
"",
"Este proyecto está bajo la Licencia MIT - ve el archivo [LICENSE.md](LICENSE) para detalles",
"",
"---",
"",
"## Consejos Adicionales",
"",
"Aquí hay algunos consejos extra para aprovechar al máximo tu README:",
"",
"- Mantén cada sección lo más concisa posible. Evita la información innecesaria, ya que puede ser abrumadora para el lector.",
"- Asegúrate de que tus instrucciones de instalación, despliegue sean detalladas y precisas. Si hay pasos adicionales que el lector necesita tomar (como instalar dependencias extra), asegúrate de", "incluirlos.",
"- Los visuales (imágenes, GIFs) son muy útiles para transmitir rápidamente lo que hace tu proyecto y cómo usarlo. Si puedes, incluye capturas de pantalla de tu aplicación en acción o GIFs que", "demuestren su uso.",
"",
"---",
"",
"⌨️ con ❤️ por [Williams Hernández](https://github.com/hernandw) 😊",
""
			

		],
	 	"description": "create a readme"
	 },


*/

/* 

"create a gitignore p": {
	"prefix": "git",
	"body": [
		
"# Created by https://www.toptal.com/developers/gitignore/api/node,visualstudiocode,macos,linux,windows",
"# Edit at https://www.toptal.com/developers/gitignore?templates=node,visualstudiocode,macos,linux,windows",
"",
"### Linux ###",
"*~",
"",
"# temporary files which can be created if a process still has a handle open of a deleted file",
".fuse_hidden*",
"",
"# KDE directory preferences",
".directory",
"",
"# Linux trash folder which might appear on any partition or disk",
".Trash-*",
"",
"# .nfs files are created when an open file is removed but is still being accessed",
".nfs*",
"",
"### macOS ###",
"# General",
".DS_Store",
".AppleDouble",
".LSOverride",
"",
"# Icon must end with two \r",
"Icon",
"",
"",
"# Thumbnails",
"._*",
"",
"# Files that might appear in the root of a volume",
".DocumentRevisions-V100",
".fseventsd",
".Spotlight-V100",
".TemporaryItems",
".Trashes",
".VolumeIcon.icns",
".com.apple.timemachine.donotpresent",
"",
"# Directories potentially created on remote AFP share",
".AppleDB",
".AppleDesktop",
"Network Trash Folder",
"Temporary Items",
".apdisk",
"",
"### macOS Patch ###",
"# iCloud generated files",
"*.icloud",
"",
"### Node ###",
"# Logs",
"logs",
"*.log",
"npm-debug.log*",
"yarn-debug.log*",
"yarn-error.log*",
"lerna-debug.log*",
".pnpm-debug.log*",
"",
"# Diagnostic reports (https://nodejs.org/api/report.html)",
"report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json",
"",
"# Runtime data",
"pids",
"*.pid",
"*.seed",
"*.pid.lock",
"",
"# Directory for instrumented libs generated by jscoverage/JSCover",
"lib-cov",
"",
"# Coverage directory used by tools like istanbul",
"coverage",
"*.lcov",
"",
"# nyc test coverage",
".nyc_output",
"",
"# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)",
".grunt",
"",
"# Bower dependency directory (https://bower.io/)",
"bower_components",
"",
"# node-waf configuration",
".lock-wscript",
"",
"# Compiled binary addons (https://nodejs.org/api/addons.html)",
"build/Release",
"",
"# Dependency directories",
"node_modules/",
"jspm_packages/",
"",
"# Snowpack dependency directory (https://snowpack.dev/)",
"web_modules/",
"",
"# TypeScript cache",
"*.tsbuildinfo",
"",
"# Optional npm cache directory",
".npm",
"",
"# Optional eslint cache",
".eslintcache",
"",
"# Optional stylelint cache",
".stylelintcache",
"",
"# Microbundle cache",
".rpt2_cache/",
".rts2_cache_cjs/",
".rts2_cache_es/",
".rts2_cache_umd/",
"",
"# Optional REPL history",
".node_repl_history",
"",
"# Output of 'npm pack'",
"*.tgz",
"",
"# Yarn Integrity file",
".yarn-integrity",
"",
"# dotenv environment variable files",
".env",
".env.development.local",
".env.test.local",
".env.production.local",
".env.local",
"",
"# parcel-bundler cache (https://parceljs.org/)",
".cache",
".parcel-cache",
"",
"# Next.js build output",
".next",
"out",
"",
"# Nuxt.js build / generate output",
".nuxt",
"dist",
"",
"# Gatsby files",
".cache/",
"# Comment in the public line in if your project uses Gatsby and not Next.js",
"# https://nextjs.org/blog/next-9-1#public-directory-support",
"# public",
"",
"# vuepress build output",
".vuepress/dist",
"",
"# vuepress v2.x temp and cache directory",
".temp",
"",
"# Docusaurus cache and generated files",
".docusaurus",
"",
"# Serverless directories",
".serverless/",
"",
"# FuseBox cache",
".fusebox/",
"",
"# DynamoDB Local files",
".dynamodb/",
"",
"# TernJS port file",
".tern-port",
"",
"# Stores VSCode versions used for testing VSCode extensions",
".vscode-test",
"",
"# yarn v2",
".yarn/cache",
".yarn/unplugged",
".yarn/build-state.yml",
".yarn/install-state.gz",
".pnp.*",
"",
"### Node Patch ###",
"# Serverless Webpack directories",
".webpack/",
"",
"# Optional stylelint cache",
"",
"# SvelteKit build / generate output",
".svelte-kit",
"",
"### VisualStudioCode ###",
".vscode/*",
"!.vscode/settings.json",
"!.vscode/tasks.json",
"!.vscode/launch.json",
"!.vscode/extensions.json",
"!.vscode/*.code-snippets",
"",
"# Local History for Visual Studio Code",
".history/",
"",
"# Built Visual Studio Code Extensions",
"*.vsix",
"",
"### VisualStudioCode Patch ###",
"# Ignore all local history of files",
".history",
".ionide",
"",
"### Windows ###",
"# Windows thumbnail cache files",
"Thumbs.db",
"Thumbs.db:encryptable",
"ehthumbs.db",
"ehthumbs_vista.db",
"",
"# Dump file",
"*.stackdump",
"",
"# Folder config file",
"[Dd]esktop.ini",
"",
"# Recycle Bin used on file shares",
"$RECYCLE.BIN/",
"",
"# Windows Installer files",
"*.cab",
"*.msi",
"*.msix",
"*.msm",
"*.msp",
"",
"# Windows shortcuts",
"*.lnk",
"",
"# End of https://www.toptal.com/developers/gitignore/api/node,visualstudiocode,macos,linux,windows",
	],
  "description": "code snippet of gitignore"
  },





*/


/*

"create a server commonjs": {
    "prefix": "server5",
    "body": [
      "const express = require('express');",
      "const app = express();",
      "const PORT = process.env.PORT || 3000;",
      "",
      "",
      "app.get('/', (req, res) => res.send('Hello World!'));",
      "",
      "",
      "app.listen(PORT, () => console.log(`Example app listening on port http://localhost:\\${PORT}`));"
    ]
  },

  "create a server es6": {
    "prefix": "server6",
    "body": [
      "import express from 'express';",
      "const app = express();",
      "const PORT = process.env.PORT || 3000;",
      "",
      "",
      "app.get('/', (req, res) => res.send('Hello World!'));",
      "",
      "",
      "app.listen(PORT, () => console.log(`Example app listening on port http://localhost:\\${PORT}`));"
    ]
  }





*/